database_file: netlas_sslbl_malicious_hosts.csv

sslbl_url: "https://sslbl.abuse.ch/blacklist/sslblacklist.csv" # URL of the SSL Certificate Blacklist CSV file

# Configuration for retry delays
max_retries: 10  # Define number of retries in case of errors
initial_delay: 1  # Initial delay in seconds between retries
max_delay: 60     # Maximum delay in seconds

csv_chunk_size: 80 # Number of lines per request MAX=90

log_changes: true
log_file: change.log

sslbl_cert_url: "https://sslbl.abuse.ch/ssl-certificates/sha1/"
netlas_host_url: "https://app.netlas.io/host/"